window.CARD_DATA = [
  {
    id: "A-1",
    series: "A",
    title: "L’Enseigne de Gersaint / The Shop Sign《店铺招牌》",
    author: "让·安托万·华托 · Jean-Antoine Watteau",
    year: "1720",
    desc: "作为早期的商业展示与艺术品交易橱窗空间。艺术品不再只存在于宫廷或私人收藏中，而是被放进商店，以商品的方式面对公众。商品被摆出来、被排列、被看见，才开始产生欲望。",
    meaning: "这幅画夸大了Gersaint狭窄的精品店的规模，在巴黎市中心的中世纪巴黎圣母院桥上，几乎只不过是一个带有小后店的永久展位，既创造又追随时尚，因为他向贵族客户提供艺术品和豪华琐事。",
    img: "images/A-1.jpg",
    thumb: "thumbs/A-1.jpg"
  },
  {
    id: "A-2",
    series: "A",
    title: "《Fresh Widow》",
    author: "Marcel Duchamp",
    year: "1920",
    desc: "杜尚把一扇真正意义上的“窗”变成了艺术品，却故意让它失去窗户最基本的功能：观看外部。所以这里橱窗第一次可以被理解为：让你看见，却不让你进入。",
    meaning: "杜尚对视觉与感知的主题充满兴趣；在这里，人们期待透过窗玻璃看到风景，却被不透明的黑色皮革打破，杜尚坚持“每天都要像擦鞋一样擦亮”。",
    img: "images/A-2.png",
    thumb: "thumbs/A-2.jpg"
  },
  {
    id: "A-3",
    series: "A",
    title: "Salvador Dalí × Bonwit Teller",
    author: "Salvador Dalí",
    year: "1939",
    desc: "这是艺术家与商业机构围绕橱窗展示权发生直接冲突的经典事件。因为它让橱窗第一次从一个“展示物品的地方”变成了一个权力现场：谁决定展示什么？谁决定怎么展示？艺术家、商店和观众之间谁拥有观看的控制权？展示开始具有政治性。",
    meaning: "Dalí为Bonwit Teller设计了“Day / Night”两组超现实主义橱窗，但商场方面因公众投诉而修改、移除了部分展示内容。Dalí随后强烈抗议，并最终造成著名的橱窗破裂事件。",
    img: "images/A-3.jpg",
    thumb: "thumbs/A-3.jpg"
  },
  {
    id: "A-4",
    series: "A",
    title: "《Window Display, Bonwit Teller》",
    author: "Andy Warhol",
    year: "1961",
    desc: "橱窗从商业展示空间变成了艺术与消费文化相互转换的接口。沃霍尔早期波普艺术作品直接进入百货公司的商业橱窗，与服装模特和商品一起面对街上的消费者。它打破了“艺术应该在美术馆、商品应该在商店”的界线。橱窗不再只是展示艺术的地方，而成为艺术与商业互相借用语言的地方。",
    meaning: "1961年4月，Warhol的五幅早期Pop绘画第一次公开展示，就是出现在Bonwit Teller的橱窗中；其中包括 Little King、Superman、Saturday's Popeye、Before and After 和 Advertisement。",
    img: "images/A-4.jpg",
    thumb: "thumbs/A-4.jpg"
  },
  {
    id: "A-5",
    series: "A",
    title: "《Shop Window / Rotozaza III》",
    author: "Jean Tinguely",
    year: "1949",
    desc: "原本用于展示商品的橱窗，在这里不再只是“摆放与观看”的界面，而成为一个真正发生事件的舞台。机械装置在玻璃之后持续运转，观众从路过者变成围观者，展示由静态陈列转向动态表演。",
    meaning: "Tinguely 将机械装置直接置于伯尔尼 Loeb 百货公司的橱窗中，使原本用于静态陈列商品的空间转化为持续发生的公共事件。机器不断击碎餐具，吸引橱窗外的人群观看，并以荒诞的破坏回应消费社会对商品的大量生产与消耗。",
    img: "images/A-5.png",
    thumb: "thumbs/A-5.jpg"
  },
  {
    id: "A-6",
    series: "A",
    title: "《The Store》",
    author: "Claes Oldenburg",
    year: "1961",
    desc: "奥尔登堡则进一步让艺术品自己变成商品。它让“展示—定价—出售”这一整套商业机制成为艺术的一部分。橱窗开始参与决定什么可以成为商品，什么可以成为艺术。",
    meaning: "1961年，Oldenburg在纽约Lower East Side开设真实店铺 The Store，把自己制作的食物、衣服、日用品等物件像普通商品一样陈列、定价并出售。MoMA称其为艺术、商品与商业之间模糊边界的重要里程碑。",
    img: "images/A-6.jpg",
    thumb: "thumbs/A-6.jpg"
  },
  {
    id: "A-7",
    series: "A",
    title: "《夜鹰》",
    author: "爱德华·霍普",
    year: "1942",
    desc: "从这一刻开始，橱窗不只是商业展示的装置，它也可以成为窥视城市生活的界面。",
    meaning: "因为在珍珠港之后，他深深地感受到笼罩着美国的一片愁云惨雾，而他也把这种感觉融入这幅画作里。在餐厅外，城市的街都是空空如也的，在餐厅里的三个人也没有对对方谈话或看着其他人，但都在自己的世界中迷失了。",
    img: "images/A-7.jpg",
    thumb: "thumbs/A-7.jpg"
  },
  {
    id: "A-8",
    series: "A",
    title: "《The Candy Store》",
    author: "Richard Estes",
    year: "1969",
    desc: "商品被陈列在玻璃之后，而城市又反射在玻璃之上。橱窗同时容纳了“里面”和“外面”：商品、广告与价格制造消费欲望，街道、建筑与观看者则被反射进同一画面。Estes 将原本透明的橱窗变成一层复杂的视觉界面，使“观看商品”本身成为作品的主题。",
    meaning: "Estes 将纽约糖果店的橱窗作为绘画主体：商品、价格牌、广告、玻璃反射、街道与建筑同时进入画面。橱窗不再只是隔开商品与观看者的透明界面，而成为内外世界交叠的视觉表面——我们既看见店里的商品，也看见玻璃反射出的城市。",
    img: "images/A-8.jpeg",
    thumb: "thumbs/A-8.jpg"
  },
  {
    id: "A-9",
    series: "A",
    title: "《Store Front Project》",
    author: "Christo",
    year: "1964",
    desc: "橱窗这里的核心已经从：“展示什么？”转向：“可见性本身如何被制造？”它反过来证明：橱窗不一定靠“展示更多”吸引人，也可以靠“隐藏更多”。看不见什么，反而会让人更想知道里面有什么。",
    meaning: "1964年的 Store Front Project 模拟商业店面，通过木材、玻璃、有机玻璃、纸、布料、电灯等材料制造一个既像展示空间、又不断阻断观看的结构。MoMA现收藏该作品。",
    img: "images/A-9.jpeg",
    thumb: "thumbs/A-9.jpg"
  },
  {
    id: "A-10",
    series: "A",
    title: "《I Shop Therefore I Am》",
    author: "Barbara Kruger",
    year: "1987",
    desc: "商品不再只是被展示的对象，而成为塑造个人身份的符号；消费者也从橱窗外的观看者，变成了主动展示自己生活方式的人。",
    meaning: "Kruger 将笛卡尔的 “I think therefore I am” 改写成 “I shop therefore I am”。画面以黑白摄影、红色边框和广告式文字构成，把消费社会最熟悉的视觉语言反过来指向观看者本身。作品将“思考”替换成“购物”，直接质疑现代社会中消费与身份之间的关系。",
    img: "images/A-10.jpg",
    thumb: "thumbs/A-10.jpg"
  },
  {
    id: "B-1",
    series: "B",
    title: "《卖火柴的小女孩》The Little Match Girl",
    author: "Hans Christian Andersen",
    year: "1845",
    desc: "橱窗＝欲望与现实之间的距离。",
    meaning: "在极寒的大年夜，赤脚的小女孩躲在墙角划亮火柴。火光的微明中，她仿佛穿透了厚重的玻璃，看见温暖的大火炉、丰盛的烤鹅以及挂满礼物的圣诞树。然而火柴熄灭后，那些触手可及的幸福瞬间荡然无存，她依然冻僵在冰冷的街头。",
    img: "images/B-1.jpg",
    thumb: "thumbs/B-1.jpg"
  },
  {
    id: "B-2",
    series: "B",
    title: "《妇女乐园》 / The Ladies’ Paradise",
    author: "Émile Zola",
    year: "1883",
    desc: "橱窗＝欲望的制造机器。",
    meaning: "新兴百货大楼的巨型陈列橱窗前人头攒动。主角德尼斯目睹了这场由丝绸、蕾丝与精美华服编织出的视觉盛宴。老板穆雷通过精心设计的光影与色彩陈列，将无形的物欲具象化，街头驻足的女性无一不被这台庞大的欲望机器所征服与吞噬。",
    img: "images/B-2.jpg",
    thumb: "thumbs/B-2.jpg"
  },
  {
    id: "B-3",
    series: "B",
    title: "《包法利夫人》 / Madame Bovary",
    author: "Gustave Flaubert",
    year: "1857",
    desc: "橱窗＝理想生活的投影幕。",
    meaning: "渴望上流社会生活的爱玛走在繁华街头，久久停留在精品店的橱窗前。玻璃内闪烁着奢华的珠宝、精致的绸缎与贵族用品，这些商品化为了她对浪漫异国与上层优雅生活的具体想象，一步步诱发并滋长了她对庸俗现实生活的极度厌倦。",
    img: "images/B-3.jpg",
    thumb: "thumbs/B-3.jpg"
  },
  {
    id: "B-4",
    series: "B",
    title: "《街头的幻象》 / Street Haunting: A London Adventure",
    author: "Virginia Woolf",
    year: "1927",
    desc: "橱窗＝城市的观看界面。",
    meaning: "叙述者以买铅笔为由漫步于冬日夜间的伦敦街头。她行至光彩照人的商业橱窗前，将视线停留在闪烁的珠宝与华丽的衣裳上。玻璃不仅映射出商品，也映出街头过客的身影，使她沉浸于这种作为现代都市人特有的“纯粹观看”体验中。",
    img: "images/B-4.jpg",
    thumb: "thumbs/B-4.jpg"
  },
  {
    id: "B-5",
    series: "B",
    title: "《达洛维夫人》 / Mrs Dalloway",
    author: "Virginia Woolf",
    year: "1925",
    desc: "橱窗＝公共观看的社会界面。",
    meaning: "在伦敦邦德街的繁华街区，达洛维夫人与众多市民一同围观手套店与珠宝店的橱窗。此时一辆神秘的黑色轿车缓缓驶过，橱窗前的公众目光瞬间被吸引并汇聚在一起。橱窗与街头交织成一个公共场域，将不同阶层行人的社会心理短暂地连接了起来。",
    img: "images/B-5.jpg",
    thumb: "thumbs/B-5.jpg"
  },
  {
    id: "B-6",
    series: "B",
    title: "《尤利西斯》 / Ulysses",
    author: "James Joyce",
    year: "1922",
    desc: "橱窗＝欲望与窥视的界面。",
    meaning: "主角布鲁姆漫步在都柏林街头，在一间服装店的橱窗前驻足。他隔着玻璃注视着内衣与时装的陈列，内心激起了对肉体与性的复杂联想。玻璃的反射将他窥视商品的目光与自我内心隐秘的欲望纠缠在一起，完成了心理流派的视觉凝视。",
    img: "images/B-6.jpg",
    thumb: "thumbs/B-6.jpg"
  },
  {
    id: "B-7",
    series: "B",
    title: "《呼啸山庄》 / Wuthering Heights",
    author: "Emily Brontë",
    year: "1847",
    desc: "橱窗＝不可抵达的边界。",
    meaning: "在一个暴风雪之夜，洛克伍德住在呼啸山庄的旧房间里，梦见已故的凯瑟琳。她的幽灵在紧闭的窗外哭泣挣扎，试图穿过窗户抓住他的手。玻璃窗在这里化为一道冰冷而绝望的生死藩篱，隔绝了爱、死亡与无法重聚的痛苦记忆。",
    img: "images/B-7.png",
    thumb: "thumbs/B-7.jpg"
  },
  {
    id: "B-8",
    series: "B",
    title: "《双城记》 / A Tale of Two Cities",
    author: "Charles Dickens",
    year: "1859",
    desc: "橱窗＝自我观看的镜子。",
    meaning: "卡顿在深夜的伦敦街头漫无目的地游荡。他走到一家装有镜子的店铺橱窗前停下脚步，借着玻璃的反射仔细打量并整理自己的衣领与头发。在这个短暂而安静的瞬间，他透过橱窗的镜像审视着自己颓废的人生，为后来的自我牺牲埋下了心理伏笔。",
    img: "images/B-8.jpg",
    thumb: "thumbs/B-8.jpg"
  },
  {
    id: "B-9",
    series: "B",
    title: "《变形记》 / The Metamorphosis",
    author: "Franz Kafka",
    year: "1915",
    desc: "橱窗＝观看关系的倒置。",
    meaning: "变成巨型甲虫后的格里高尔被家人关在房间里。他艰难地爬上窗台，凝视着窗外荒凉的街道。昔日他作为家庭支柱透过橱窗观看外部世界，如今自己却沦为被至亲嫌恶、囚禁在房间这一“橱窗”内部的异类，完成了观看与被观看地位的残酷倒置。",
    img: "images/B-9.jpg",
    thumb: "thumbs/B-9.jpg"
  },
  {
    id: "B-10",
    series: "B",
    title: "《了不起的盖茨比》 / The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: "1925",
    desc: "橱窗＝自我展示的幻象。",
    meaning: "盖茨比为了吸引戴茜的注意，将自己的豪宅打造成一座灯火通明的全景舞台。他经常站在高大的落地窗前，隔海凝视对岸戴茜家码头的绿灯。他将自己的财富、身份与整个生命都装进这个精心布置的幻象橱窗里，向外界展示着一场刻意为之的执念。",
    img: "images/B-10.png",
    thumb: "thumbs/B-10.jpg"
  },
  {
    id: "C-1",
    series: "C",
    title: "Le Bon Marché百货商店",
    author: "巴黎",
    year: "19世纪",
    desc: "现代“window shopping”的开端之一。店里的商品 → 变成街上的景观。",
    meaning: "19世纪城市空间发生变化，商品逐渐从店铺内部被推到街道边缘；大型玻璃橱窗让商品与路人之间建立起一种新的关系。Le Bon Marché 后来又把橱窗发展成节庆、故事和场景展示。其官方历史资料甚至将1893年的圣诞橱窗作为重要节点，1909年进一步出现了机械化的动态橱窗。",
    img: "images/C-1.png",
    thumb: "thumbs/C-1.jpg"
  },
  {
    id: "C-2",
    series: "C",
    title: "阿姆斯特丹 De Wallen 红灯区橱窗",
    author: "荷兰",
    year: "20世纪初",
    desc: "人变成橱窗中被消费的商品。商品橱窗 → 人的橱窗。",
    meaning: "20世纪初，阿姆斯特丹当局对街头招揽行为进行限制。到了1930年前后，De Wallen 一带已经出现一种非常特殊的做法：妓女不能站在门口向路人招揽顾客，但可以坐在临街的窗户后面。于是原本应该是“建筑采光用”的窗户，被转化成了一个人与陌生人之间进行交易的展示界面。女性坐在窗后，窗帘半开，路人从街道上可以直接看见她们；顾客如果有意向，再通过窗户、门或者其他方式与她联系。",
    img: "images/C-2.jpg",
    thumb: "thumbs/C-2.jpg"
  },
  {
    id: "C-3",
    series: "C",
    title: "King George VI 葬礼",
    author: "英国",
    year: "1952",
    desc: "橱窗从“展示物品的窗口”变成了“公共屏幕”。让街上的人看一个本来无法进入的“远方事件”。",
    meaning: "1952年2月15日，英国国王乔治六世葬礼当天，伦敦 Baker Street 一家商店把电视机放在橱窗中播放葬礼直播/转播，街上的人聚集在橱窗外观看电视。当时的照片由 Daily Mirror/Mirrorpix 保存。",
    img: "images/C-3.jpeg",
    thumb: "thumbs/C-3.jpg"
  },
  {
    id: "C-4",
    series: "C",
    title: "Ford Rouge Glass Plant",
    author: "美国",
    year: "1923",
    desc: "工厂作为橱窗媒介让公众看见生产。公众 → 生产过程。",
    meaning: "1924年，Ford Rouge 开始向公众开放参观。游客不再只是站在工厂外面看一栋建筑，而是被组织进入这个庞大的工业生产体系，观看其中的钢铁生产、装配线以及部分玻璃厂等生产环节。1924—1982年间，Rouge 长期接待公众参观；高峰时期一年可以达到约25万人次。",
    img: "images/C-4.jpg",
    thumb: "thumbs/C-4.jpg"
  },
  {
    id: "C-5",
    series: "C",
    title: "Selfridges × Suffragette妇女运动",
    author: "英国",
    year: "20世纪初",
    desc: "橱窗第一次成为政治的“公共界面”。运动发起者通过击碎橱窗表达立场。",
    meaning: "英国妇女参政运动曾直接将商店橱窗作为政治斗争对象。所谓 “vitrinoclasm”，就是通过破坏、干预橱窗来打断原本的消费观看机制，把商业展示空间变成政治信息的传播场。相关研究专门把这一现象定义为对橱窗所代表的“商品化凝视”的抵抗。",
    img: "images/C-5.png",
    thumb: "thumbs/C-5.jpg"
  },
  {
    id: "C-6",
    series: "C",
    title: "Selfridges Christmas Windows橱窗剧场",
    author: "英国",
    year: "1909",
    desc: "橱窗开始制造“想象”。",
    meaning: "1909年Selfridges开业时，创始人 Harry Gordon Selfridge 就把橱窗作为重要的商业体验，并在开业时通过戏剧化的方式揭开橱窗；商店后来因极具吸引力的橱窗而闻名，尤其是圣诞期间。London Museum也将其描述为一种艺术形式。人们甚至会专门来到 Oxford Street 看橱窗，而不是为了立即购买。",
    img: "images/C-6.jpeg",
    thumb: "thumbs/C-6.jpg"
  },
  {
    id: "C-7",
    series: "C",
    title: "《Ondria Tanner and Her Grandmother Window-Shopping》",
    author: "美国",
    year: "1956",
    desc: "橱窗作为种族隔离下的“可见但不可进入”。",
    meaning: "1956年，Parks 为《Life》杂志前往阿拉巴马州记录一个黑人家庭在种族隔离制度下的日常生活。其中一张照片正是 Ondria Tanner 和祖母站在百货商店橱窗外“window-shopping”。橱窗里面排列着白色皮肤的儿童人体模特和服装，而黑人祖孙只能站在玻璃外观看。Gordon Parks Foundation 和美国国家非裔美国人历史文化博物馆均保存了这张作品。",
    img: "images/C-7.jpeg",
    thumb: "thumbs/C-7.jpg"
  },
  {
    id: "C-8",
    series: "C",
    title: "Apple旗舰店玻璃幕墙",
    author: "Apple Fifth Avenue Glass Cube",
    year: "2006",
    desc: "橱窗从一个展示商品的容器变成展示品牌世界的入口。",
    meaning: "apple品牌通过高度透明的界面把一个原本隐藏在地下的商业空间变成城市公共视觉的一部分，此处真正被展示的是其品牌本身的运营过程。",
    img: "images/C-8.jpeg",
    thumb: "thumbs/C-8.jpg"
  },
  {
    id: "C-9",
    series: "C",
    title: "Carnaby Street「Lady Jane」",
    author: "英国",
    year: "1966",
    desc: "真人模特代替橱窗中的商品成为展示媒介。",
    meaning: "1966年5月，Carnaby Street 的女装店 Lady Jane 直接把两名模特放进临街橱窗，让她们像“活的人体模特”一样在橱窗中换衣服。围观人群迅速聚集到街道上，甚至造成交通阻塞，警方介入，店主 Henry Moss 最终因阻碍道路被罚款。相关历史照片至今保存下来。",
    img: "images/C-9.png",
    thumb: "thumbs/C-9.jpg"
  },
  {
    id: "C-10",
    series: "C",
    title: "Baby Incubator / Coney Island 婴儿橱窗",
    author: "美国",
    year: "20世纪初",
    desc: "橱窗展示不可商品化的新生命本身。",
    meaning: "20世纪初，Martin Couney 在纽约 Coney Island 的 Luna Park、Dreamland 等场所展示早产儿保育箱。游客付费进入观看，而这些收入反过来承担婴儿的护理费用；家长并不需要支付医疗费用。1904年的资料明确记载，游客可以付费进入展馆，婴儿被放置在保育箱中接受护理。PBS的历史资料直接描述游客走近成排的保育箱，透过玻璃观看里面的早产儿。",
    img: "images/C-10.jpeg",
    thumb: "thumbs/C-10.jpg"
  },
  {
    id: "D-1",
    series: "D",
    title: "神龛",
    author: "—",
    year: "—",
    desc: "被隔离的物获得特殊的观看权。橱窗把普通商品从日常环境中抽离，以距离、中心与光线赋予它特殊价值；像神龛中的圣物，越不可触碰，越强化凝视。",
    meaning: "橱窗把普通商品从日常环境中抽离，以距离、中心与光线赋予它特殊价值。",
    img: "images/D-1.jpeg",
    thumb: "thumbs/D-1.jpg"
  },
  {
    id: "D-2",
    series: "D",
    title: "剧场",
    author: "—",
    year: "—",
    desc: "陈列空间变成一场没有台词的演出。模特、商品、灯光与布景被安排在固定的观看平面上，街道成为观众席；每一个经过的人，都短暂地成为观众。",
    meaning: "街道成为观众席；每一个经过的人，都短暂地成为观众。",
    img: "images/D-2.jpeg",
    thumb: "thumbs/D-2.jpg"
  },
  {
    id: "D-3",
    series: "D",
    title: "温室",
    author: "—",
    year: "—",
    desc: "透明边界里的人工世界。温室通过玻璃结构创造一个与外部环境分离的内部生态。植物、光线、温度和湿度共同组成一个被控制、被保护的世界。",
    meaning: "玻璃结构创造一个与外部环境分离的内部生态。",
    img: "images/D-3.jpeg",
    thumb: "thumbs/D-3.jpg"
  },
  {
    id: "D-4",
    series: "D",
    title: "镜厅",
    author: "—",
    year: "—",
    desc: "当观看不断反射自身。橱窗玻璃既展示内部，又映出外部；商品、街道与观看者相互叠加，最后连“正在观看的人”也成为橱窗中的一部分。",
    meaning: "连“正在观看的人”也成为橱窗中的一部分。",
    img: "images/D-4.jpeg",
    thumb: "thumbs/D-4.jpg"
  },
  {
    id: "D-5",
    series: "D",
    title: "痛包（Itabag）",
    author: "—",
    year: "—",
    desc: "随身携带的视觉自我：故意使用透明材质将个人物品或动漫周边毫无保留地暴露在外，向街头主动宣示身份信仰。",
    meaning: "向街头主动宣示身份信仰。",
    img: "images/D-5.jpeg",
    thumb: "thumbs/D-5.jpg"
  },
  {
    id: "D-6",
    series: "D",
    title: "雪花球",
    author: "—",
    year: "—",
    desc: "雪花球将建筑、人物和自然景象压缩在透明球体之中，形成一个独立于现实之外的小型世界。观看者可以从外部观察其中的景象，却永远无法真正进入。",
    meaning: "观看者可以从外部观察其中的景象，却永远无法真正进入。",
    img: "images/D-6.jpeg",
    thumb: "thumbs/D-6.jpg"
  },
  {
    id: "D-7",
    series: "D",
    title: "朋友圈 / 小红书的“精修九宫格”",
    author: "—",
    year: "—",
    desc: "现实中杂乱、平庸的生活被彻底隐去，只有被筛选、精修、精心打光的“理想生活切片”（高档餐厅、旅行风景、精致自拍）被打包放入九个方格中。这个屏幕界面就是现代人的数字橱窗，向外界陈列着自己渴望被他人认可的人设与阶层品味。",
    meaning: "这个屏幕界面就是现代人的数字橱窗。",
    img: "images/D-7.jpeg",
    thumb: "thumbs/D-7.jpg"
  },
  {
    id: "D-8",
    series: "D",
    title: "IKEA 家具展示空间",
    author: "—",
    year: "—",
    desc: "家具展示空间不再单独展示产品，而是将沙发、灯具、植物、装饰和空间关系组合成完整生活场景。消费者看到的不只是一件家具，而是一种被提前设计好的未来生活。观看者不再站在外部，而是进入展示之中。",
    meaning: "观看者不再站在外部，而是进入展示之中。",
    img: "images/D-8.jpeg",
    thumb: "thumbs/D-8.jpg"
  },
  {
    id: "D-9",
    series: "D",
    title: "阳台",
    author: "—",
    year: "—",
    desc: "每一个阳台都是一个带有物理边框的立体小展柜。阳台上的晾衣、绿植、闲坐等私人日常，被透明玻璃或开口框定在建筑外表皮上。对于街头路人（观众）而言，整座大楼就像是一个由无数“生活切片”堆叠而成的巨型多格商业橱窗。",
    meaning: "整座大楼就像是一个由无数“生活切片”堆叠而成的巨型多格商业橱窗。",
    img: "images/D-9.jpeg",
    thumb: "thumbs/D-9.jpg"
  },
  {
    id: "D-10",
    series: "D",
    title: "楚门的小镇",
    author: "—",
    year: "—",
    desc: "《楚门的世界》中，整座小镇都是一个巨大的摄影棚。街道、住宅、人际关系和日常生活，都被设计成一个持续运行的展示系统。对于屏幕之外的观众而言，整个城市就是一面巨大的橱窗；生活本身成为被观看、被消费的对象。",
    meaning: "整个城市就是一面巨大的橱窗；生活本身成为被观看、被消费的对象。",
    img: "images/D-10.jpeg",
    thumb: "thumbs/D-10.jpg"
  }
];
